version: "3.9"
services:
  csvserver:
    build: . 
    ports:
      - "9393:9300"
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml
